// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides channel assistant suggestions based on channel title and member list.
 *
 * - getChannelAssistantSuggestions - A function that returns channel assistant suggestions.
 * - ChannelAssistantInput - The input type for the getChannelAssistantSuggestions function.
 * - ChannelAssistantOutput - The return type for the getChannelAssistantSuggestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ChannelAssistantInputSchema = z.object({
  channelTitle: z.string().describe('The title of the channel.'),
  memberList: z.array(z.string()).describe('A list of usernames in the channel.'),
});
export type ChannelAssistantInput = z.infer<typeof ChannelAssistantInputSchema>;

const ChannelAssistantOutputSchema = z.object({
  topicSuggestion: z.string().describe('A suggested topic for the channel.'),
  descriptionSuggestion: z.string().describe('A suggested description for the channel.'),
  automationSuggestions: z
    .array(z.string())
    .describe(
      'A list of suggested automations for the channel, such as welcome messages, scheduled event invites, and ice-breakers.'
    ),
});
export type ChannelAssistantOutput = z.infer<typeof ChannelAssistantOutputSchema>;

export async function getChannelAssistantSuggestions(
  input: ChannelAssistantInput
): Promise<ChannelAssistantOutput> {
  return channelAssistantSuggestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'channelAssistantSuggestionsPrompt',
  input: {schema: ChannelAssistantInputSchema},
  output: {schema: ChannelAssistantOutputSchema},
  prompt: `You are a channel assistant that provides suggestions for a channel based on its title and member list.

Given the following channel title and member list, suggest a relevant topic, description, and automations to streamline channel setup and engagement.

Channel Title: {{{channelTitle}}}
Member List: {{#each memberList}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}

Topic Suggestion:
Description Suggestion:
Automation Suggestions (welcome messages, scheduled event invites, ice-breakers):`,
});

const channelAssistantSuggestionsFlow = ai.defineFlow(
  {
    name: 'channelAssistantSuggestionsFlow',
    inputSchema: ChannelAssistantInputSchema,
    outputSchema: ChannelAssistantOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
